name: Android CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ANDROID_SDK_ROOT: ${{ github.workspace }}/android-sdk
      ANDROID_HOME: ${{ github.workspace }}/android-sdk

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          cache-read-only: false

      # 1) Descargar e instalar cmdline-tools
      - name: Install cmdline-tools
        shell: bash
        run: |
          set -eux
          mkdir -p "$ANDROID_SDK_ROOT/cmdline-tools"
          curl -sSL https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -o cmdtools.zip
          unzip -q cmdtools.zip -d "$ANDROID_SDK_ROOT/cmdline-tools"
          mv "$ANDROID_SDK_ROOT/cmdline-tools/cmdline-tools" "$ANDROID_SDK_ROOT/cmdline-tools/latest"
          rm -f cmdtools.zip
          echo "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin" >> $GITHUB_PATH
          echo "$ANDROID_SDK_ROOT/platform-tools" >> $GITHUB_PATH
          echo "$ANDROID_SDK_ROOT/build-tools/34.0.0" >> $GITHUB_PATH

      # 2) Aceptar licencias e instalar paquetes usando la ruta completa a sdkmanager
      - name: Install Android packages
        shell: bash
        run: |
          set -eux
          "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager" --licenses <<<'y'
          "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager" --install "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      # 3) Generar gradlew 8.7 y compilar Debug
      - name: Generate Gradle Wrapper 8.7
        shell: bash
        run: |
          set -eux
          gradle wrapper --gradle-version 8.7 --distribution-type all
          chmod +x ./gradlew

      - name: Build Debug
        shell: bash
        run: |
          set -eux
          ./gradlew :app:assembleDebug --no-daemon -S

      - name: Upload APKs
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/debug/*.apk
          if-no-files-found: error
