name: Android CI (smoke)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Print tool versions
        run: |
          echo "JAVA:"
          java -version
          echo "GIT:"
          git --version
          echo "PWD:"
          pwd
          echo "List repo:"
          ls -la          
