name: Android CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      # Instala Android SDK y acepta licencias
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          packages: |
            platform-tools
            platforms;android-34
            build-tools;34.0.0

      # Instala Gradle sin wrapper
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.2.1

      # Compila APK release
      - name: Build (assembleRelease)
        run: gradle :app:assembleRelease --no-daemon

      # Sube el APK como artefacto descargable
      - name: Upload APKs
        uses: actions/upload-artifact@v4
        with:
          name: app-apk
          path: app/build/outputs/apk/release/*.apk
          if-no-files-found: error
