name: Android CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          packages: |
            cmdline-tools;latest
            platforms;android-34
            build-tools;34.0.0

      # Si tu proyecto ya trae gradlew, forzamos Gradle 8.7 en el wrapper
      - name: Update Gradle wrapper to 8.7 (if present)
        run: |
          if [ -f ./gradlew ]; then
            chmod +x ./gradlew
            ./gradlew wrapper --gradle-version 8.7
          fi

      - name: Build (assembleRelease)
        run: |
          if [ -f ./gradlew ]; then
            chmod +x ./gradlew
            ./gradlew --version
            ./gradlew assembleRelease --no-daemon --stacktrace
          else
            echo "No gradlew found. Using Gradle 8.7 binary."
            curl -sLo gradle.zip https://services.gradle.org/distributions/gradle-8.7-bin.zip
            unzip -q gradle.zip
            ./gradle-8.7/bin/gradle assembleRelease --no-daemon --stacktrace
          fi

      - name: Upload APKs
        uses: actions/upload-artifact@v4
        with:
          name: app-apks
          # Ruta genérica: sirve tanto si el módulo se llama "app" como "aplicación"
          path: "**/build/outputs/apk/release/*.apk"
          if-no-files-found: error
