name: Android CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ANDROID_SDK_ROOT: ${{ github.workspace }}/android-sdk
      ANDROID_HOME: ${{ github.workspace }}/android-sdk

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # Instala cmdline-tools y los paquetes base del SDK
      - name: Install Android SDK (cmdline-tools + packages)
        run: |
          set -eux
          mkdir -p "$ANDROID_SDK_ROOT/cmdline-tools"
          curl -sSL https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -o cmdtools.zip
          unzip -q cmdtools.zip -d "$ANDROID_SDK_ROOT/cmdline-tools"
          mv "$ANDROID_SDK_ROOT/cmdline-tools/cmdline-tools" "$ANDROID_SDK_ROOT/cmdline-tools/latest"
          rm -f cmdtools.zip

          # Usar sdkmanager con ruta absoluta dentro de ESTE paso
          SDKM="$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager"
          yes | "$SDKM" --licenses
          "$SDKM" --install "platform-tools" "platforms;android-34" "build-tools;34.0.0"

          # Añadir a PATH para los SIGUIENTES pasos
          echo "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin" >> $GITHUB_PATH
          echo "$ANDROID_SDK_ROOT/platform-tools" >> $GITHUB_PATH
          echo "$ANDROID_SDK_ROOT/build-tools/34.0.0" >> $GITHUB_PATH

      # Compila con Gradle 8.7 aunque no tengas gradlew en el repo
      - name: Build (assembleRelease) with Gradle 8.7
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.7
          build-root-directory: .
          arguments: :app:assembleRelease --no-daemon -S

      # Sube el APK generado como artefacto
      - name: Upload APKs
        uses: actions/upload-artifact@v4
        with:
          name: app-apk
          path: app/build/outputs/apk/release/*.apk
          if-no-files-found: error
